
import  Head  from 'next/head'

import '../styles/globals.css'
import styles from '../styles/Home.module.css'

function MyApp({ Component, pageProps }) {
  return (
  
  <div className='bg-[#fdf9f0] overflow-hidden'>
      <Head>
        <title>DZ Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/abc.png" />
      </Head>
   
     <Component {...pageProps} />

    
  </div>
 )
}

export default MyApp
